### ISSUE TITLE
What should I do if the √N is not an integer?

### ISSUE THREAD

**Issue by ChaiJinhao** [HazyResearch/m2#11]
**What should I do if the √N is not an integer?**

**Comment by Edenzzzz** [comment]
Just find the closest integer factor. That's also in their code.

**Comment by ChaiJinhao** [comment]
> Just find the closest integer factor. That's also in their code.

Thank you！！！

**Comment by DanFu09** [comment]
Yep, that's the right thing to do. We have a follow-up paper out now where we dive deeper into the tradeoffs for higher-order decompositions (focusing on the fixed FFT case, but many of the insights apply to the general case as well): https://github.com/HazyResearch/flash-fft-conv

We'll be moving the code into this codebase soon!
